name: Run all tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out project
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install --with-deps chromium

      - name: Start the server
        run: uvicorn app.main:app &

      - name: Wait for the server to start
        run: sleep 10s

      - name: Run tests
        run: python3 -m pytest -s -v --browser chromium tests
